[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mint_pay = "4WRQYnzUNyQ4gMQNct7TqDmKVheHKgA8PzNvmeVaRLZq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
